version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "4000:4000"
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
